name: agent
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15

  #网络请求
  dio: ^4.0.6
  get: ^4.6.5
  oktoast: ^3.3.1
  permission_handler: ^10.2.0
  encrypt: ^5.0.1
  web_socket_channel: ^2.2.0
  decimal: any
  url_launcher: ^6.1.5
  package_info_plus: ^3.0.2
  webview_flutter: ^4.0.2
  flutter_picker: ^2.0.5
  better_open_file: ^3.6.4
  path_provider: any
  image_picker: ^0.8.5+3
  audioplayers: ^1.0.1
  flutter_svg: ^1.1.6

  image_gallery_saver: 1.7.1
  # 播放器
  video_player: any
  chewie: ^1.3.6
  # 屏幕旋转
  auto_orientation: ^2.2.1
  # 亮度和音量调节
  brightness_volume: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sound/
